#+TITLE: DM1 Week 01 Teach
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty
#+SETUPFILE: ../theme-bigblow.setup

[[elisp:(find-file-other-window%20"../week00/00-prepare.org")][Read Instructions]]
[[elisp:(browse-url-of-file%20(org-html-export-to-html))][Export to HTML and Browse]]
[[elisp:(org-clock-report%201)][Insert/Update Clock Summary Report]]

* TODO Think About and Discuss the Census-Taker Problem
  After thinking about it individually, and then collectively arriving at a
  consensus by following the instructions given in class, write up your report
  below.

#+BEGIN_QUOTE
  A census-taker knocks on the door and a woman answers the door. She tells the
  census-taker that she lives in the house with her =nd= daughters.

  \ldquo{}And what are their ages?\rdquo the census-taker asked.

  \ldquo{}I won\rsquo{}t tell you --- but I will tell you that =pa= is the product of their
  ages\rdquo, replied the woman.

  \ldquo{}That\rsquo{}s not enough information\rdquo, said the census-taker.

  \ldquo{}Okay, the sum of their ages is =sa=\rdquo, said the woman.

  \ldquo{}That\rsquo{}s still not enough information! Please, is there something more you can
  tell me?\rdquo the census-taker implored.

  \ldquo{}Yes, there is. =sm=\rdquo, revealed the woman.
#+END_QUOTE
**** Variable Values Revealed

  | Variable | Description           |                          Value |
  |----------+-----------------------+--------------------------------|
  | =nd=     | Number of daughters   |                              3 |
  | =pa=     | Product of their ages |                             36 |
  | =sa=     | Sum of their ages     |                             13 |
  | =sm=     | Something more        | My oldest daughter likes cats. |

* TODO Report
#+begin_info
  Your answer goes here.
#+end_info
