#+TITLE: DM1 Week 02 Teach
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty
#+SETUPFILE: ../theme-bigblow.setup

[[elisp:(find-file-other-window%20"../week00/00-prepare.org")][Read Instructions]]
[[elisp:(browse-url-of-file%20(org-html-export-to-html))][Export to HTML and Browse]]
[[elisp:(org-clock-report%201)][Insert/Update Clock Summary Report]]
* TODO Think and Discuss
  First a comment, then a puzzle. In the limited time we have to scratch the
  surface of DM, we can just barely, barely scratch the surface of logic (and
  its companion --- touched on even more lightly --- proof). If you want a much
  richer, fuller engagement with logic and proof, I urge you to take PHIL 205
  Logic and Critical Thinking, offered through the Department of Humanities and
  Philosophy, and expertly taught by my good friend and colleague, Ross Baron,
  of the Department of Religion. The course he taught that I sat in on recently
  used the book tersely titled /Logic/ by Stan Baronett, which is the source of
  this statement of the puzzle (most likely a problem --- /NOT/ an exercise!):

#+begin_note
  Scientists, philosophers, mathematicians, detectives, logicians, and
  physicians all face logical problems. How do they go about solving them? For
  insights, try your own hand at a challenge, the /problem of the hats/.

  Once you are given the facts of the case, be aware of how you attack the
  problem, how you take it apart, what you place emphasis on, your avenues of
  pursuit, and plausible conjectures. The answer requires \ldquo{}seeing\rdquo a key move.

  Here is the challenge: A teacher comes to class with a box and shows the
  contents of the box to the students. It contains three white hats, two red
  hats, and nothing else. There happen to be only three students in this class,
  and the teacher tells them that he is going to blindfold each one and then
  place one of the five hats on each of their heads. The remaining two hats will
  then be placed back in the box, so no one can see them once the blindfolds are
  removed. If anyone can tell what color hat they have on their heads, then the
  teacher will give that student an A. But the students are not allowed to
  guess: They must be able to /prove/ they have that color hat.

  The teacher removes the blindfold from the first student, who is now able to
  see the color of the hats on the other two students --- but not his own. The
  first student looks carefully at the other two hats, thinks silently for a
  while, and says he does not know the color of his hat. The teacher then
  removes the blindfold from the second student. He, too, looks at the hats on
  the other two students, thinks for a while, and says he does not know the
  color of his hat. (As before, this student does /not/ say aloud the color of
  the hats he sees on the other two students\rsquo{} heads.) Now, just as the teacher
  is about to remove the blindfold from the third student, she says that she
  knows exactly the color of the hat on her head. In fact, she doesn\rsquo{}t even need
  to see the hats of the other two students to know this.

  Can you see how she did it? No information is being held back, no tricks are
  being played, and no word games are used. All the information necessary to
  solve the problem is contained in its description. There are three
  possibilities for you to consider. Which is correct?

  1. She cannot possibly know what color hat she has on her head.
  2. She has a red hat and can prove it.
  3. She has a white hat and can prove it.
#+end_note

  After thinking about it individually, and then collectively arriving at a
  consensus by following the instructions given in class, write up your report
  below.
* TODO Report
#+begin_info
  Your answer goes here.
#+end_info
