#+TITLE: DM1 Week 09 Ponder/Prove
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t d:(not "HINT")
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty
#+SETUPFILE: ../theme-bigblow.setup

[[elisp:(find-file-other-window%20"../week00/00-prepare.org")][Read Instructions]]
[[elisp:(browse-url-of-file%20(org-html-export-to-html))][Export to HTML and Browse]]
[[elisp:(org-clock-report%201)][Insert/Update Clock Summary Report]]
* Exercises
  Exercise, to be precise:
** TODO LND
#+begin_note
  Why do 17 characters require 5 bits per character for a fixed-length encoding.
  What in general is required for /n/ different characters?
#+end_note
#+begin_info
  Your answer goes here.
#+end_info
* Problems
  No optional problems this week.
** TODO LTI
#+begin_note
  Use the tree and the code given below to decode the message
  =00010010000111010111011011010111100110000010111101100011101011110=.

  Best would be to write a =decode= function that has the same signature as
  =find-leaf= and calls =find-leaf= as a helper function.

  Now decode the longer message
  =0001001000111001110101110110110101111001100000101111011000111010111100111=
  and explain the reason for the perhaps surprising result.

#+BEGIN_SRC elisp :results silent
  (require 'cl)

  (defvar tree
    '((("n" "t") (("i" "o") (" " ""))) ("e" ("h" "r"))))

  (defun get-value (node)
    (and (stringp node) node))

  (defun get-left (node)
    (and (listp node) (first node)))

  (defun get-right (node)
    (and (listp node) (second node)))

  (defun find-leaf (encoded tree)
    (if (get-value tree)
        (cons tree encoded)
      (let ((first-char (elt encoded 0))
            (rest-of-encoded (substring encoded 1)))
        (case first-char
          (?0 (find-leaf rest-of-encoded (get-left tree)))
          (?1 (find-leaf rest-of-encoded (get-right tree)))
          (t "")))))
#+END_SRC
#+end_note
#+begin_info
  Your answer goes here.
#+end_info
** TODO YDQ
#+begin_note
  What is the tie-breaking rule used when deciding where to insert into the
  queue in this Huffman tree construction? Implement this rule in elisp code,
  and compare it to the one used by [[http://huffman.ooz.ie][this tool]]. Does it matter what tie-breaking
  rule you use? Why or why not?
#+end_note
#+begin_info
  Your answer goes here.
#+end_info
** TODO YTR
#+begin_note
  Construct the Huffman tree for and build the bitstring encoding the string
  "cookbooknook".

  What is the average number of bits per character with this encoding?

  What is the compression ratio achieved using this tree\rsquo{}s encoding of
  the string?
#+end_note
#+begin_info
  Your answer goes here.
#+end_info
** TODO LGO
#+begin_note
  Using the "cookbooknook" encoding, the bitstring =1011001110= decodes into one
  English word. What word is it?
#+end_note
#+begin_info
  Your answer goes here.
#+end_info
** TODO YIV
#+begin_note
   Draw the trees created by calling the =try-it-out= and the =build-tree=
   functions, the latter called with at least three different height arguments.
#+end_note
#+begin_info
  Your answer goes here.
#+end_info
* Puzzles
  No puzzles this week.
* TODO Identify Collaborators
  Identify your collaborators and the contribution of each, in the following way:

  - Joseph Smith :: In particular, he helped me understand \dots.
  - Benjamin Franklin :: He helped brainstorm ideas for \dots. 
  -  :: etc. 
