#+TITLE: DM1 Week 06 Prepare
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty
#+SETUPFILE: ../theme-bigblow.setup

[[elisp:(find-file-other-window%20"../week00/00-prepare.org")][Read Instructions]]
[[elisp:(browse-url-of-file%20(org-html-export-to-html))][Export to HTML and Browse]]
[[elisp:(org-clock-report%201)][Insert/Update Clock Summary Report]]
* TODO Read MNO through MNA from [[https://rickneff.github.io/metaphors-be-with-you.html][The Book]].
* TODO Learn How to Customize a Variable
  Many of you already know how to stop emacs from asking you every time you go
  to evaluate a code block, 

  /Evaluate this emacs-lisp code block on your system? (y or n)/

  If you don\rsquo{}t already know, read on. First, ponder: Why this prompt? Evaluating
  numbers or simple numeric expressions is a pretty benign activity, but that\rsquo{}s
  not true of evaluating some lisp code, which potentially can do bad things.
  Hence the safeguard confirmation prompt. But that gets tedious after a while.
  You can disable this prompt by setting a special controlling flag variable to
  nil. Specifically:

  SPC SPC customize-variable

  Then at the prompt type \ldquo{}org-confirm-babel-evaluate\rdquo (without the quotes), and
  hit Enter to bring up the Customization buffer.

  TAB (10 times) to the button labeled /Toggle/, and click on it or hit Enter to
  press it. The state message will change to say:

  STATE: EDITED, shown value does not take effect until you set or save it.

  Shift-TAB (3 times) back to the /Apply and Save/ button and hit Enter again. 
  That changes the state message to:

  STATE: Saved and set.

  Dismiss the Customization buffer by typing q.
* TODO Answer What is True
  You know what to do. 
  - [ ] I left it as is, or customized the org-confirm-babel-evaluate variable
    to my liking.
